// <auto-generated />
namespace CoPortal.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Addedmoreinfoforstudentandlecturer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addedmoreinfoforstudentandlecturer));
        
        string IMigrationMetadata.Id
        {
            get { return "201804170856588_Added more info for student and lecturer"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
