language: node_js
node_js:
  - stable
addons:
  apt:
    packages:
      - sshpass
  ssh_known_hosts:
    - $ADDRESS:$PORT
cache:
  apt: true
  directories:
    - node_modules
install:
  - cd ./co-portal/client
  - npm install
  - npm run build
  - cd ../../
  - bash ./deploy.sh "$PASSWORD" "$PORT" "$USERNAME" "$ADDRESS" "$PROJECT_FOLDER" "$PROJECT_PORT" "CoportalDev"
  - cd ./co-portal/server
  - npm install
script:
  - npm rebuild
  - npm run build
  - cd ../../
  - echo "Running the script that builds the server"
deploy:
  - provider: script
    script: bash ./deploy.sh "$PASSWORD" "$PORT" "$USERNAME" "$ADDRESS" "$PROJECT_FOLDER" "$PROJECT_PORT" "CoportalDev"
    on:
      branch: develop
  - provider: script
    script: bash ./deploy.sh "$PASSWORD" "$PORT" "$USERNAME" "$ADDRESS" "$PROJECT_LIVE_FOLDER" "$PROJECT_LIVE_PORT" "CoportalLive"
    on:
      branch: master